- app/pubspec.lock
- app/pubspec.yaml
- feat: upgrade mocktail, bloc, and bloc_test
> feat: upgrade mocktail, bloc, and bloc_test

- app/android/app/build.gradle
- app/android/build.gradle
- app/android/gradle/wrapper/gradle-wrapper.properties
- build(android): upgrade to gradle 7.1.2 (https://github.com/VeryGoodOpenSource/very_good_cli/issues/364)
> build(android): upgrade to gradle 7.1.2

- .github/workflows/very_good_core.yaml
- app/pubspec.lock
- chore(deps): upgrade to Flutter 2.10.5
> chore(deps): upgrade to Flutter 2.10.5

- .github/workflows/very_good_core.yaml
- app/.github/workflows/main.yaml
- app/lib/app/view/app.dart
- app/lib/counter/view/counter_page.dart
- app/pubspec.lock
- app/pubspec.yaml
- app/windows/flutter/generated_plugins.cmake
- feat(core): upgrade to Flutter 3.0.0
> feat(core): upgrade to Flutter 3.0.0

- app/analysis_options.yaml
- app/pubspec.lock
- app/pubspec.yaml
- chore(deps): very_good_analysis ^3.0.0
> chore(deps): very_good_analysis ^3.0.0

- app/.github/workflows/main.yaml
- app/pubspec.lock
- feat: add semantic pull request workflow and upgrade to Flutter 3.0.3
> feat: add semantic pull request workflow and upgrade to Flutter 3.0.3

- .github/workflows/generate_very_good_core.yaml
- .github/workflows/very_good_core.yaml
- app/.github/workflows/main.yaml
- app/pubspec.lock
- app/pubspec.yaml
- chore: upgrade to Flutter 3.0.4
> chore: upgrade to Flutter 3.0.4

- app/android/app/build.gradle
- chore(android): remove lintOptions override in build.gradle
> chore(android): remove lintOptions override in build.gradle

- .github/workflows/very_good_core.yaml
- app/.github/workflows/main.yaml
- app/lib/bootstrap.dart
- app/pubspec.lock
- app/pubspec.yaml
- feat: upgrade to bloc v8.1.0
- feat: upgrade to flutter 3.0.5
> feat: upgrade to bloc v8.1.0

- app/ios/Runner/Info.plist
- chore(ios): update info.plist
> chore(ios): update info.plist

- .gitignore
- src/my_app/.idea/runConfigurations/development.xml
- src/my_app/.idea/runConfigurations/production.xml
- src/my_app/.idea/runConfigurations/staging.xml
- src/my_app/.vscode/extensions.json
- src/my_app/.vscode/launch.json
- chore: include launch configurations
> chore: include launch configurations

- tool/generator/main.dart
- build: fix generated project structure
> build: fix generated project structure

- brick/CHANGELOG.md
- brick/LICENSE
- brick/README.md
- brick/brick.yaml
- chore(brick): update metadata
> chore(brick): update metadata

- .github/workflows/very_good_core.yaml
- src/my_app/.github/workflows/main.yaml
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
- feat: upgrade to Flutter 3.3 and Dart 2.18
> feat: upgrade to Flutter 3.3 and Dart 2.18

- brick/CHANGELOG.md
- brick/README.md
> chore(brick): v0.1.0

- src/my_app/analysis_options.yaml
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
- chore(deps): upgrade to very_good_analysis 3.0.2
> chore(deps): upgrade to very_good_analysis 3.0.2

- brick/CHANGELOG.md
- brick/README.md
- brick/brick.yaml
> chore: v0.1.1

- .github/workflows/very_good_core.yaml
- src/my_app/.github/workflows/main.yaml
- src/my_app/analysis_options.yaml
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
- feat: upgrade to Flutter 3.3.2 and Very Good Analysis 3.1.0
> feat: upgrade to Flutter 3.3.2 and Very Good Analysis 3.1.0

- .github/workflows/very_good_core.yaml
- src/my_app/.github/workflows/main.yaml
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
- feat: upgrade to Flutter 3.3.3
> feat: upgrade to Flutter 3.3.3

- .github/dependabot.yaml
- src/my_app/.github/dependabot.yaml
> feat: add dependabot

- .github/workflows/very_good_core.yaml
- src/my_app/.github/workflows/main.yaml
- src/my_app/ios/Flutter/AppFrameworkInfo.plist
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
- feat: upgrade to Flutter 3.3.6
> feat: upgrade to Flutter 3.3.6

- brick/CHANGELOG.md
- brick/brick.yaml
- chore: v0.1.5
- feat: upgrade to Flutter 3.3.6
- fix: add support for `GlobalCupertinoLocalizations`
> chore: v0.1.5

- .github/workflows/very_good_core.yaml
- src/my_app/.github/workflows/main.yaml
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
- feat: upgrade to Flutter 3.3.7
> feat: upgrade to Flutter 3.3.7

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.1.6

- brick/__brick__/{{project_name.snakeCase()}}/android/app/build.gradle
- brick/__brick__/{{project_name.snakeCase()}}/ios/Runner.xcodeproj/project.pbxproj
- brick/__brick__/{{project_name.snakeCase()}}/windows/runner/Runner.rc
- brick/__brick__/{{project_name.snakeCase()}}/windows/runner/main.cpp
- brick/brick.yaml
- brick/hooks/pre_gen.dart
- brick/hooks/pubspec.yaml
- tool/generator/main.dart
Adds a new `application_id` parameter that can enable users inform a custom application/bundle id for their apps.
This change will enable the closing of https://github.com/VeryGoodOpenSource/very_good_cli/issues/280.
> feat: adding application id parameter

- .github/workflows/very_good_core.yaml
- src/my_app/.github/workflows/main.yaml
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
- feat: upgrade to Flutter 3.3.8
> feat: upgrade to Flutter 3.3.8

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.1.7

- brick/hooks/pre_gen.dart
- tool/generator/main.dart
- docs: remove copyright header and license from generated code
> docs: remove copyright header and license from generated code

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.1.8

- src/my_app/web/index.html
Update the description content to `"A new Flutter project."` in `src/my_app/web/index.html` which ensures that the correct variable place holder `{{{description}}}` is generated after running `dart ./tool/generator/main.dart`.
> fix: use the correct description variable in src/my_app/web/index.html

- brick/brick.yaml
- brick/hooks/pre_gen.dart
- brick/hooks/pubspec.yaml
- deps(brick): upgrade to mason v0.1.0-dev.40
> chore(brick): upgrade to mason v0.1.0-dev.40

- .github/workflows/very_good_core.yaml
- src/my_app/.github/workflows/main.yaml
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
- feat: upgrade to Flutter 3.3.10
> feat: upgrade to Flutter 3.3.10

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.1.9

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.1.10

- .github/workflows/very_good_core.yaml
- src/my_app/.github/workflows/main.yaml
- src/my_app/lib/counter/view/counter_page.dart
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
feat: upgrade to flutter 3.7.0
> feat: upgrade to flutter 3.7.0

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.1.11

- src/my_app/android/app/src/main/AndroidManifest.xml
- src/my_app/android/build.gradle
Small changes on the android platform folder to match the files created by flutter latest stable version.
> feat: small updates to the android folder to match the latest flutter structure

- .github/workflows/very_good_core.yaml
- src/my_app/ios/Runner.xcodeproj/project.pbxproj
- src/my_app/ios/Runner/Info.plist
- src/my_app/lib/bootstrap.dart
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
- refactor: upgrade to bloc v8.1.1
> refactor: upgrade to bloc v8.1.1

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.1.12

- src/my_app/analysis_options.yaml
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
- feat: upgrade to very_good_analysis 4.0.0
> feat: upgrade to very_good_analysis 4.0.0

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.1.13

- .github/workflows/very_good_core.yaml
- src/my_app/pubspec.yaml
- chore: remove explicit Flutter version constraint
> chore: remove explicit Flutter version constraint

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.1.14

- brick/hooks/analysis_options.yaml
- brick/hooks/pubspec.yaml
- src/my_app/analysis_options.yaml
- src/my_app/pubspec.lock
- src/my_app/pubspec.yaml
Currently incompatible with very_good_cli min dart SDK (2.18.0), see [workflow](https://github.com/VeryGoodOpenSource/very_good_cli/actions/runs/4366480256/jobs/7636550957).
> fix: rollback very_good_analysis to 3.1.0

- .github/workflows/e2e.yaml
- .github/workflows/very_good_core.yaml
- tool/e2e/analysis_options.yaml
- tool/e2e/pubspec.yaml
chore: downgrade workflow flutter runtime version
> chore: downgrade workflow flutter runtime version

- brick/CHANGELOG.md
- brick/brick.yaml
> chore: v0.1.15

- .github/workflows/e2e.yaml
- .github/workflows/very_good_core.yaml
- brick/brick.yaml
- brick/hooks/analysis_options.yaml
- brick/hooks/pubspec.yaml
- src/my_app/analysis_options.yaml
- src/my_app/pubspec.yaml
- tool/e2e/analysis_options.yaml
- tool/e2e/pubspec.yaml
Related to https://github.com/VeryGoodOpenSource/very_good_cli/issues/702
> feat!: bump min Dart SDK to 2.19.0

- src/my_app/android/app/src/main/AndroidManifest.xml
Changes:
- Change application label to use flavour's label.
Closes: https://github.com/VeryGoodOpenSource/very_good_cli/issues/724
---
Before:
After:
> fix: use correct app label

- README.md
Added documentation on how to generate translation files on README.md
Due to lack of activity in #275 I'm opening this PR addressing those changes
Fixes #259 
Closes #275
> docs: translation generation in README.md

- brick/__brick__/{{project_name.snakeCase()}}/lib/app/view/app.dart
- src/my_app/lib/app/view/app.dart
This PR updates `app` in the `src` and `brick` to Material 3.
> refactor: Update `app` to Material 3

- .github/workflows/e2e.yaml
- .github/workflows/very_good_core.yaml
- brick/hooks/analysis_options.yaml
- brick/hooks/pubspec.yaml
- e2e/analysis_options.yaml
- e2e/pubspec.yaml
- src/my_app/.gitignore
- src/my_app/.metadata
- src/my_app/analysis_options.yaml
- src/my_app/android/.gitignore
- src/my_app/android/gradlew
- src/my_app/android/gradlew.bat
- src/my_app/ios/Runner.xcodeproj/project.pbxproj
- src/my_app/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- src/my_app/ios/RunnerTests/RunnerTests.swift
- src/my_app/pubspec.yaml
fix: [#766](https://github.com/VeryGoodOpenSource/very_good_cli/issues/766)
fix: https://github.com/VeryGoodOpenSource/very_good_cli/issues/762
> fix: add runner tests,update analysis and update ignored files

- src/my_app/.gitignore
chore: restore vscode ignored files
> chore: restore vscode ignored files

- brick/brick.yaml
- e2e/pubspec.yaml
> chore: bump mason

- README.md
> docs: add missing README links

- CONTRIBUTING.md
- README.md
- coverage_badge.svg
> docs: update badges and typos

- CONTRIBUTING.md
- tool/release_ready.sh
> chore: add release ready script

- brick/__brick__/{{project_name.snakeCase()}}/ios/Runner.xcodeproj/project.pbxproj
Resolves https://github.com/VeryGoodOpenSource/very_good_cli/issues/948.
> fix: templated project name for Release-production flavour
